CREATE TABLE public.gpt_messages (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"content" text NULL,
	user_id uuid NULL,
	user_meta_data jsonb NULL,
	is_gpt bool NOT NULL,
	CONSTRAINT gpt_messages_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.gpt_messages IS 'GPT chat table';

CREATE TABLE public.messages (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	"content" text NULL,
	user_id uuid NULL,
	user_meta_data jsonb NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- Table Triggers

create trigger on_message_created after
insert
    on
    public.messages for each row execute function handle_new_message();

CREATE OR REPLACE FUNCTION public.handle_new_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  declare user_data jsonb;
begin
  select raw_user_meta_data into user_data from auth.users where id = new.user_id for update;
  update public.messages set user_meta_data = jsonb_build_object('name', user_data ->> 'name', 'profile_image', user_data ->> 'avatar_url') where id = new.id;
  return new;
end;
$function$
;